src/middlewares/passport/JwtStrategy.ts, src/services/AuthService.ts
1. fix:토큰페이로드에 유저 타입 추가
2. profile 초기 셋팅
=> [fix 이지수]토큰페이로드에 유저 타입 추가 및 프로파일 셋팅

prisma/migrations/20250710065525_update_schema/migration.sql, prisma/schema.prisma, prisma/seed.ts, src/app.ts, src/controllers/ProfileController.ts, src/repositories/AuthRepository.ts, src/repositories/ProfileRepository.ts, src/routes/ProfileRouter.ts, src/server.ts, src/services/ProfileService.ts
1. profile API 작업 
POST	/profile/customer	고객 프로필 생성 
PATCH /profile/customer	고객 프로필 수정 
GET	/profile/customer/:id	고객 프로필 조회 
POST	 /profile/driver	기사 프로필 생성
PATCH /profile/driver	기사 프로필 수정
GET	/profile/driver/:id	기사 프로필 상세 조회 
추가하였으나 아직 오류가 있어서 수정해야됩니다.
2. 스키마 Driver 부분 career      Int? //String에서 Int로 타입만 변경
work        Int      @default(0) //추가
=> [feat 이지수] profile API 미완성

src/app.ts, src/controllers/customerEstimate.controller.ts, src/repositories/customerEstimate.repository.ts, src/routes/customerEstimate.router.ts, src/services/customerEstimate.service.ts
- 대기 중인 견적, 상세, 견적 확정하기 api까지 완료
- 견적서 보내기 api가 있어야 테스트가 가능한 흐름이라 테스트는 나중에 하도록 하겠습니다. 
=> [김다은] 대기 중인 견적, 상세, 견적 확정하기 api까지 완료

src/controllers/notification.controller.ts
=> 알림 관련 bug fix

src/controllers/customerEstimate.controller.ts, src/repositories/customerEstimate.repository.ts, src/routes/customerEstimate.router.ts, src/services/customerEstimate.service.ts
=> [김다은] 받았던 견적 리스트 & 상세 조회 api

prisma/migrations/20250718092802_update_schema/migration.sql, prisma/migrations/20250718094727_update_schema/migration.sql, prisma/schema.prisma
스키마 수정 요구사항 전부 반영해서 올려서 좀 많이 수정됐습니다.
=> [fix 이지수] 스키마 대폭 수정

src/controllers/estimateReq.controller.ts, src/middlewares/passport/jwtStrategy.ts, src/repositories/estimateReq.repository.ts, src/routes/estimateReq.router.ts, src/services/estimateReq.service.ts
- 지정 견적 요청 로직 구현했습니다.
- 활성 견적 요청 확인, 중복 지정 방지, 최대 3명 제한 로직 추가
- **TODO**
- 알림 연동 시 기사님 필터링 부분 사용 고려할 것
=> [Feat] 지정 견적 요청 로직 구현 및 관련 리팩토링

src/controllers/driver.controller.ts, src/controllers/favorite.controller.ts, src/repositories/driver.repository.ts, src/repositories/favorite.repository.ts, src/routes/driver.router.ts, src/routes/favorite.router.ts, src/services/driver.service.ts, src/services/favorite.service.ts, src/types/index.d.ts
1. 리뷰 페이지네이션 구현했습니다.
2. 찜한 기사님 불러오기 API 구현했습니다
- 기사님 찾기랑 기사님 상세에 auth 미들웨어 추가했는데 이러니까 비로그인 상태에서는 작동이 안되어서 내일 지수님께 수정 요청드릴예정입니다
=> [FEAT] 찜하기, 리뷰 페이지네이션

src/controllers/estimateReq.controller.ts, src/middlewares/passport/jwtStrategy.ts, src/routes/estimateReq.router.ts, src/services/estimateReq.service.ts
- 활성 견적 조회하는 api(`estimate-request/active`) 추가 구현했습니다
=> feat: 활성 견적 조회 api 추가

src/controllers/driver.controller.ts, src/repositories/driver.repository.ts, src/routes/driver.router.ts
1. 로그인이랑 비로그인 상태일 때 API 엔드포인트 분리했습니다.
2. 서비스 부분 검색 수정했습니다.
=> [FIX] find driver

package-lock.json, package.json, src/controllers/customerEstimate.controller.ts, src/controllers/driver.controller.ts, src/controllers/estimateReq.controller.ts, src/controllers/notification.controller.ts, src/repositories/address.repository.ts, src/repositories/auth.repository.ts, src/repositories/customerEstimate.repository.ts, src/repositories/driver.repository.ts, src/repositories/notification.Repository.ts, src/routes/notification.router.ts, src/services/auth.service.ts, src/services/customerEstimate.service.ts, src/services/notification.service.ts, src/services/review.service.ts, src/types/notification.type.ts, src/utils/notificationMessage.ts, src/utils/notificationMoveDaySchedule.ts
- 회원가입을 할 경우 알림이 생성됩니다.
- 견적 요청을 할 경우 고객/기사에게 알림이 생성됩니다.
- 도달한 기사가 없을 경우 관련한 알림이 고객에게 생성됩니다.
- 최신화 완료..!
=> feat: notification BE

src/controllers/auth.controller.ts, src/middlewares/passport/socialStrategy.ts, src/services/auth.service.ts
=> [Fix 이지수]  소셜로그인 구현 완료 및 충돌 수정

src/controllers/driver.controller.ts, src/repositories/estimateReq.repository.ts, src/services/estimateReq.service.ts, src/services/notification.service.ts, src/types/notification.type.ts, src/utils/notificationMessage.ts, src/utils/notificationMoveDaySchedule.ts
- 고객에게 견적을 전송할 경우 알림이 생성됩니다.
- 고객이 견적을 확정할 경우 고객/기사에게 알림이 생성됩니다.
=> [notification] 견적전송, 확정 알림 BE

src/controllers/driver.controller.ts, src/controllers/notification.controller.ts, src/repositories/notification.Repository.ts, src/routes/notification.router.ts, src/services/notification.service.ts, src/types/notification.type.ts, src/utils/moveReminder.ts, src/utils/notificationMessage.ts, src/utils/notificationMoveDaySchedule.ts
- 불필요한 주석 삭제했습니다.
- 알림 관련 파일 분리했습니다.
=> chor: 주석삭제

src/services/notification.service.ts
- 알림이 생성되면 실시간으로 알 수 있도록 버그 수정
=> [bug fix] 실시간 알림

src/services/notification.service.ts, src/types/notification.type.ts, src/utils/notificationMessage.ts
- 지역 관련 텍스트가 스키마 raw 값으로 설정되어 있어서 변경했습니다.
=> fix: 알림 지역 텍스트명 수정

src/controllers/driver.controller.ts, src/repositories/driver.repository.ts, src/repositories/favorite.repository.ts, src/routes/driver.router.ts, src/services/driver.service.ts
1. 찜한 기사님 불러오는 API 수정했습니다.
2. 안쓰는 기사 정보 업데이트 API 삭제했습니다.
=> [FIX]: 찜한 기사님 api 수정

src/controllers/customerEstimate.controller.ts, src/repositories/customerEstimate.repository.ts, src/services/customerEstimate.service.ts
=> [김다은] 내견적관리 api 부분 수정

src/services/driver.service.ts
1. 지정 견적 요청 여부 정보를 기사님 상세정보 불러올 때 같이 불러올 수 있도록 했습니다.
=> [FIX] 지정 견적 요청 여부 전달

src/controllers/customerEstimate.controller.ts, src/controllers/favorite.controller.ts, src/repositories/customerEstimate.repository.ts, src/repositories/favorite.repository.ts, src/services/customerEstimate.service.ts, src/services/favorite.service.ts, src/services/notification.service.ts
내견적관리에 알림기능 합치기 + 찜하기 목록 api 수정
- 일단 에러까지 수정해서 알림 기능 합치긴 했는데 혹시 빠진 부분있거나 추가가 덜 된 부분도 있을 수 있습니다..!
=> [김다은] 내견적관리에 알림기능 합치기 + 찜하기 목록 api 수정

prisma/schema.prisma, src/repositories/driver.repository.ts, src/services/notification.service.ts
- 반려한 고객견적요청 리스트 조회 로직변경 + 알림에러해결
- 견적상세조회 api 오류해결
=> [기능] 반려요청 페이지 및 견적상세 페이지 API 연동

src/controllers/review.controller.ts, src/repositories/driver.repository.ts, src/repositories/review.repository.ts, src/routes/review.router.ts, src/services/notification.service.ts, src/services/review.service.ts, src/types/review.type.ts
- 리뷰 POST, GET, DELETE API 구현 했습니다.
- 페이지네이션 구현 남았습니다.
- 기사님 별점 업뎃기능 구현했습니다.
=> Feat: 리뷰 POST, GET, DELETE 구현 및 수정 

src/controllers/review.controller.ts, src/repositories/review.repository.ts, src/services/review.service.ts
=> Feat:리뷰 페이지네이션 적용위한 API 수정

src/controllers/auth.controller.ts, src/repositories/auth.repository.ts
=> [fix: 이지수] name 정보 출력하는 api에 프로필 정보 추가

openapi.yaml
=> docs: 주소, 견적요청 Swagger 작성

openapi.yaml
=> 알림 swagger 작성

src/controllers/customerEstimate.controller.test.ts, src/repositories/customerEstimate.repository.test.ts, src/services/customerEstimate.service.test.ts
내견적관리 api 테스트 코드 작성
- router 제외하고 각 파일에 테스트 코드 작성했습니다.
- controller에서 알림 호출 부분이 실패가 떠서 일단 제거하고 했습니다. 추후에 알림 부분도 테스트 코드 작성 되면 그때 같이 반영하겠습니다. 
=> [김다은] 내견적관리 api 테스트 코드 작성

src/controllers/customerEstimate.controller.test.ts
controller에서 알림 호출 추가 수정했습니다. 
=> [김다은] controller에서 알림 호출 에러 해결

package-lock.json, package.json, src/services/estimateReq.service.test.ts, src/services/estimateReq.service.ts
- 견적 요청 시 오늘 날짜도 허용되도록 날짜 유효성 로직 개선했습니다.
- 테스트 코드도 같이 리팩토링했습니다.
=> feat: 견적 요청 날짜 유효성 수정

src/services/auth.service.ts, src/services/profile.service.ts
이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정2
=> [fix 이지수]이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정2

src/utils/getCookieDomain.ts
fix:이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정복원
=> fix:이름 유효성 검사 제거 및 소셜로그인 토큰 도메인 재설정복원

src/app.ts, src/controllers/shareEstimate.controller.ts, src/routes/shareEstimate.router.ts
공유하기 api
- 견적서 공유하기는 인증 토큰이 필요하기 때문에 공유용 토큰을 만들어서 api를 생성했습니다. 
=> [김다은] 공유하기 api

src/repositories/driver.repository.ts
=> [FIX] 리뷰 오류 수정

src/controllers/shareEstimate.controller.ts
견적서 공유하기 최종 수정
- 고객, 기사 타입 추가했습니다. 
=> [김다은] 견적서 공유하기 최종 수정

src/controllers/customerEstimate.controller.ts, src/repositories/customerEstimate.repository.ts
견적확정 건수 증가
- 견적 확정하기 시 확정 건수(work)가 증가됩니다.
- 프론트에선 별도 수정 필요없습니다. (새로고침, 페이지 이동 없이도 바로 최신화 필요하다면 수정 가능성 있음)
=> [김다은] 견적확정 건수 증가

src/repositories/driverPrivate.repository.test.ts
=> [Fix] 테스트 수정까지 완료

package-lock.json, package.json, src/app.ts, src/instrument.ts
- 센트리 설정 완료 
`npm install @sentry/node --save`
=> [황수정] 센트리 적용

src/controllers/estimateReq.controller.ts, src/services/estimateReq.service.ts
=> feat: 견적 요청 에러메세지 다국어 추가

.github/workflows/deploy.yml
=> fix: 환경변수 설정

src/controllers/estimateReq.controller.test.ts, src/services/estimateReq.service.test.ts
=> fix: 견적요청 테스트 실패 코드 수정

.github/workflows/deploy.yml
=> fix:deploy 폴더 수정

src/services/auth.service.ts
- 소셜로그인 할 경우 알림로직 추가
- 테스트는 못해봄..
=> [황수정] 소셜로그인 환영알림

src/repositories/customerEstimate.repository.ts
=> [김다은] 내견적관리 api에서 driver.id 추가

src/controllers/auth.controller.ts, src/middlewares/authLimiter.ts, src/routes/auth.router.ts
요청제한 미들웨어 authLimiter의 경로를 컨트롤러에서 미들웨어로 옮기고 설정 값을 max → limit 으로 변경한 후 10분에 10회의 api 요청만 허용하게 바꿨습니다.
=> [fix 이지수] 요청제한 미들웨어 코드 수정

src/app.ts, src/utils/cronScheduler.test.ts, src/utils/cronScheduler.ts
- app.ts에서 cron 작업을 별도 모듈로 분리
- 테스트 환경(NODE_ENV=test)에서는 cron 스케줄러 실행 방지
- node-cron 모킹을 위한 테스트 파일 추가
=> [Refactor] cron스케줄러 모듈화 및 테스트환경 조건부처리

package-lock.json, package.json, src/controllers/profile.controller.ts, src/middlewares/uploadMiddleware.ts, src/types/multer-s3.d.ts
=> [Feat/cloudfront 이지수] s3앞에 클라우드 프론트 추가

src/controllers/profile.controller.test.ts
=> [fix:profile 이지수]테스트 타입 에러 해결

src/repositories/review.repository.ts, src/services/review.service.ts
=> Fix:review

jest.config.js, src/integration-test/notification.test.ts, tsconfig.json
- 가입환영 메시지 생성에 대한 통합테스트 코드 작성했습니다.
=> [황수정] notification supertest

package.json, src/integration-test/auth.test.ts, src/middlewares/authLimiter.ts, src/routes/auth.router.ts, src/utils/resetDB.ts
=> [Test/auth 이지수] auth 통합 테스트 코드 작성

src/integration-test/estimateReq.test.ts
- EstimateRequest 통합 테스트 작성했습니다.
=> test: EstimateRequest 통합 테스트 작성

src/integration-test/auth.test.ts, src/services/auth.service.ts, src/services/profile.service.ts
=> [Fix/authnametest 이지수] 이름유효성검사 추가 및 auth 테스트 계정 수정

jest.config.js, jest.setup.js, package-lock.json, package.json, src/app.ts, src/middlewares/cacheMiddleware.ts, src/routes/auth.router.ts, src/routes/customerEstimate.router.ts, src/routes/driver.router.ts, src/routes/driverPrivate.router.ts, src/routes/estimateReq.router.ts, src/routes/favorite.router.ts, src/routes/notification.router.ts, src/routes/review.router.ts, src/routes/shareEstimate.router.ts
- redis 적용했습니다.
- 테스트 환경일 때 캐싱 적용되지 않도록 분리했습니다.
- 하나씩 테스트해본다고 GET 메소드마다 미들웨어 붙여놨는데, 내일 한번에 적용시킬 수 있도록 수정할 예정입니다.
- npm i 설치 부탁드립니다.
- 오류가 날 수 있습니다 ㅠㅠ 확인 해주시고 문제 생기면 바로 말씀 주세요
=> feat(cache): Redis 적용 및 테스트 환경 분리

src/integration-test/estimateReq.test.ts, src/middlewares/cacheMiddleware.ts
- 관련 부분 인증 테스트에서 오류가 나 함께 실패하는 것 같아서 기능 테스트는 아니라 일단 삭제 처리했습니다.
=> fix: estimateReq 통합테스트 fail 수정

src/integration-test/driverPrivate.test.ts
- 통합테스트 대상: 
GET /estimate-requests - 모든 견적 요청 조회
POST /estimate-requests/:requestId/estimates - 견적 생성
POST /estimate-requests/:requestId/reject - 견적 요청 반려
GET /estimates - 내 견적 조회
GET /estimates/:estimateId - 견적 상세 조회
GET /estimate-requests/rejected - 반려된 견적 요청 조회
=> [Test] 기사님 통합테스트작성

src/repositories/profile.repository.ts, src/services/profile.service.ts
=> [Fix/profilenickname 이지수] 기사 닉네임 중복 검사 로직 및 메세지 추가

src/integration-test/auth.test.ts
=> [Fix/profilenickname 이지수]  auth 테스트 코드 에러 수정

src/middlewares/cacheMiddleware.ts, src/routes/translateRouter.ts
- GET 말고 다른 메소드로 캐싱될 수 있도록 수정했습니다.
- 번역 라우터에도 캐싱미들웨어 추가했습니다.
=> fix: redis 적용 메소드 확장

src/middlewares/cacheMiddleware.ts, src/routes/translateRouter.ts
=> fix: cacheMiddleware 초기화
